### ISSUE TITLE
ApnsConfig object's properties are null

### ISSUE THREAD

**Issue by tacoman667** [UTurista/FCMessaging#2]
Trying to create the `ApnsConfig` class doesn't instantiate the `headers` and `payload` property objects so we are unable to add anything to them due to null exceptions. I do not see where there might be a builder or some other mechanism to instantiate these.

Is this just not yet started on?

**Comment by UTurista** [comment]
IOS and Web related classes are still just empty shells, eventually I'll start on them but for now I'm messing with android only.

With IOS I would even had to check if I'll just expose the Dictionary as is or if its worth to make a proper wrapper with whatever IOS fields uses (never messed with IOS notifications).

Feel free to make a PR for this.
